# Generated by Django 4.2.4 on 2023-08-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('info', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('custom_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
