# Generated by Django 4.2.4 on 2023-08-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scraperesult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperesult',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraperesult',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
