# Generated by Django 4.2.4 on 2023-08-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_scraperesult_image_alter_scraperesult_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperesult',
            name='custom_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
